### ISSUE TITLE
\"missing field `burst_colours`\", line: 1, column: 2867

### ISSUE THREAD

**Issue by sapphonie** [brownian-motion/discord-autodelete#7]
Howdy, installed thru docker-compose;
```docker-compose.yml
secrets:
  discord_bot_token:
    file: ./token.txt

services:
  discord_autodelete:
    container_name: "discord-autodelete"
    # build: https://github.com/brownian-motion/discord-autodelete.git
    # git cloned locally
    build: ./
    restart: unless-stopped
    network_mode: host
    volumes:
      - "./config:/app/config"
    environment:
      - "CONFIG_PATH=/app/config/config.yaml"
      - "DISCORD_BOT_TOKEN_PATH=/run/secrets/discord_bot_token"
    secrets:
      - discord_bot_token # mounted into /run/secrets/discord_bot_token
```
Config:

```
guilds:
- id: '<>'
  channels:
  # delete everything from channel <#> that gets older than 2 minutes:
  - id: '<>'
    delete_older_than:
      minutes: 2
  # delete every message with images/videos from channel <#637575874339525219> that gets older than a day and a half:
  #- id: '637575874339525219'
  #  just_images: true
  #  delete_older_than:
  #    days: 1
  #    hours: 12
```
Error msg:
```
discord-autodelete  | {"args":{"discord_bot_token_path":"/run/secrets/discord_bot_token","config_path":"/app/config/config.yaml","dry_run":false,"poll_interval_minutes":2,"log_level":"info"},"level":"INFO","message":"starting","target":"discord_autodelete","timestamp":1750891930754}
discord-autodelete  | {"level":"INFO","message":"reloading config","target":"discord_autodelete","timestamp":1750891930754}
discord-autodelete  | {"level":"INFO","message":"deleting","target":"discord_autodelete","timestamp":1750891930754}
discord-autodelete  | {"level":"INFO","message":"Deleting messages","num_channels":1,"num_guilds":1,"target":"discord_autodelete::deleter","timestamp":1750891930754}
discord-autodelete  | {"channel":{"id":"<channel-id>","name":"<channel-name>"},"error":"Framework(Json(Error(\"missing field `burst_colours`\", line: 1, column: 2867)))","file":"src/deleter.rs","guild":{"id":"<id>","name":"<guild name>"},"level":"ERROR","line":43,"message":"Error loading messages","module":"discord_autodelete::deleter","target":"discord_autodelete::deleter","timestamp":1750891931394}
discord-autodelete  | {"level":"INFO","message":"Finished","target":"discord_autodelete::deleter","timestamp":1750891931394}
discord-autodelete  | {"level":"INFO","message":"sleeping","num_minutes":2,"target":"discord_autodelete","timestamp":1750891931394}
```

Bot doesn't appear online nor does it delete any messages. Any help would be nice. Thanks!
